// Writes the shared Alex Merced network plumbing into every HTML page of
// agenticlakehouse.com.
//
// This site is plain static HTML committed to git, and Netlify serves the
// committed files as they are (there is no build step). So run this BEFORE you
// commit, any time you add or edit a page or after network/ is regenerated:
//
//   node scripts/apply-network.mjs
//
// It reads network/network-head.html and network/network.json. Both are
// generated by alexmercedcom/scripts/build-network-shared.mjs; never edit them
// by hand. Between these markers in each page it writes:
//
//   <!-- network:head:start --> ... <!-- network:head:end -->
//       the GA4 tag, the canonical Person JSON-LD, and twitter:site
//   <!-- network:footer:start --> ... <!-- network:footer:end -->
//       the "Work with Alex" CTA strip, then the site footer: this site's own
//       links plus the network groups from network.json
//
// Markers are inserted on first run (head before </head>; footer around the
// existing <footer class="site-footer">). The script also removes hand-written
// Person JSON-LD that the head file now supplies (author and publisher
// references become {"@id": "https://alexmerced.com/#alexmerced"}), removes
// old hand-written gtag snippets, and switches twitter meta to name=.
// It needs Node 18+ and has no dependencies.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const PERSON_ID = 'https://alexmerced.com/#alexmerced';

const head = readFileSync(join(ROOT, 'network/network-head.html'), 'utf8').trim();
const network = JSON.parse(readFileSync(join(ROOT, 'network/network.json'), 'utf8'));
const { footer, cta, twitterSite } = network;
if (!footer?.groups?.length) throw new Error('network.json has no footer groups');

const esc = (v) => String(v).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const ext = (url) => (/^https?:\/\//.test(url) ? ' target="_blank" rel="noopener"' : '');
const li = (url, label, extra = '') => `<li><a href="${esc(url)}"${ext(url)}${extra}>${esc(label)}</a></li>`;

// ---------------------------------------------------------------------------
// This site's own footer links (not network links). Edit these here.
// ---------------------------------------------------------------------------
const SITE_EXPLORE = [
  ['/what-is-agentic-lakehouse/', 'What is an agentic lakehouse?'],
  ['/agentic-lakehouse-architecture/', 'Reference architecture'],
  ['/agentic-bi/', 'Agentic BI'],
  ['/kb/', 'Agentic lakehouse glossary'],
  ['/videos/', 'Video explainers'],
  ['/books/', 'Books'],
  ['/#faq', 'Common questions'],
];
const SITE_COMMUNITY = [
  ['https://luma.com/agenticlakehouse', 'Agentic Lakehouse events', 'cta_luma_community'],
  ['https://luma.com/DataLakehouseHub', 'Data Lakehouse Hub events'],
  ['https://join.slack.com/t/thedatalakehousehub/shared_invite/zt-274yc8sza-mI2zhCW8LGkOh1uxuf8T5Q', 'Data Lakehouse Hub Slack'],
  ['https://join.slack.com/t/data-events/shared_invite/zt-38vgrooy9-U9ral_gr3NAz_Siih1QwmQ', 'Data Events Slack'],
  ['https://join.slack.com/t/datatechcommunity/shared_invite/zt-12xrk4qmd-y~6jUFFd7kdaLhgLURKwoA', 'Data & Tech Slack'],
  ['https://www.reddit.com/r/datalakehouseandai/', 'r/datalakehouseandai'],
  ['https://www.linkedin.com/company/data-lakehouse-hub/', 'Data Lakehouse Hub on LinkedIn'],
  ['https://www.youtube.com/@alexmerceddata', 'Alex Merced Data & AI on YouTube'],
];
const SITE_NEWSLETTERS = [
  ['https://amdatalakehouse.substack.com', 'AI newsletter, Thursdays'],
  ['https://amdatalakehouse.substack.com', 'Apache lakehouse newsletter, Fridays'],
];

const headBlock = `${head}\n<meta name="twitter:site" content="${esc(twitterSite)}">`;

const ctaHtml = cta
  ? `<section class="network-cta" aria-labelledby="network-cta-heading">
      <div class="container network-cta__inner">
        <h2 class="network-cta__heading" id="network-cta-heading">${esc(cta.heading)}</h2>
        <div class="network-cta__links">
${cta.links.map((l) => `          <a class="btn btn-secondary" href="${esc(l.url)}"${ext(l.url)} data-network-event="${esc(l.event)}">${esc(l.label)}</a>`).join('\n')}
        </div>
      </div>
    </section>`
  : '';

const footerHtml = `<footer class="site-footer">
      <div class="container">
        <div class="footer-grid">
          <div class="footer-brand">
            <a href="/" class="footer-logo-link" aria-label="Agentic Lakehouse Home">
              <span class="footer-logo-text">Agentic<br><strong>Lakehouse</strong></span>
            </a>
            <p class="footer-tagline">Reference architecture, working patterns, and a community for the engineers and architects building the agentic lakehouse.</p>
          </div>
          <div class="footer-col">
            <h4 class="footer-col-title">Explore</h4>
            <ul class="footer-nav-list">
${SITE_EXPLORE.map(([u, t]) => `              ${li(u, t)}`).join('\n')}
            </ul>
          </div>
          <div class="footer-col">
            <h4 class="footer-col-title">Community</h4>
            <ul class="footer-nav-list">
${SITE_COMMUNITY.map(([u, t, ev]) => `              ${li(u, t, ev ? ` data-network-event="${esc(ev)}"` : '')}`).join('\n')}
            </ul>
          </div>
        </div>
        <nav class="footer-network" aria-label="The Alex Merced Network">
          <div class="footer-network__grid">
${footer.groups.map((g) => `            <div class="footer-col">
              <h4 class="footer-col-title">${esc(g.title)}</h4>
              <ul class="footer-nav-list">
${g.links.map((l) => `                ${li(l.url, l.title)}`).join('\n')}
              </ul>
            </div>`).join('\n')}
          </div>
          <p class="footer-network__all"><a href="${esc(footer.allSitesUrl)}" target="_blank" rel="noopener">${esc(footer.allSitesLabel)} &rarr;</a></p>
        </nav>
        <nav class="footer-run" aria-label="Free weekly newsletters">
          <div class="footer-run-title">Free Weekly Newsletters</div>
          <ul class="footer-run-list">
${SITE_NEWSLETTERS.map(([u, t]) => `            ${li(u, t, ' data-network-event="cta_newsletter"')}`).join('\n')}
          </ul>
        </nav>
        <div class="footer-bottom">
          <p>&copy; ${new Date().getFullYear()} AgenticLakehouse.com. A resource by <a href="https://alexmerced.com" target="_blank" rel="noopener">Alex Merced</a>, written for data engineers and architects.</p>
        </div>
      </div>
    </footer>`;

const footerBlock = [ctaHtml, footerHtml].filter(Boolean).join('\n    ');

// ---------------------------------------------------------------------------
const replaceBlock = (html, name, content) => {
  const re = new RegExp(`(<!-- network:${name}:start -->)[\\s\\S]*?(<!-- network:${name}:end -->)`);
  return html.replace(re, () => `<!-- network:${name}:start -->\n${content}\n<!-- network:${name}:end -->`);
};

const isAlex = (o) => o && typeof o === 'object' && !Array.isArray(o) &&
  (o['@type'] === 'Person') && (o['@id'] === PERSON_ID || o.name === 'Alex Merced');

// Replace nested Alex Person objects with an @id reference.
function refPeople(node) {
  if (Array.isArray(node)) return node.map(refPeople);
  if (node && typeof node === 'object') {
    if (isAlex(node)) return { '@id': PERSON_ID };
    const out = {};
    for (const [k, v] of Object.entries(node)) out[k] = refPeople(v);
    return out;
  }
  return node;
}

function cleanJsonLd(json) {
  let data;
  try { data = JSON.parse(json); } catch { return null; }
  // Drop top-level Person nodes (the head file carries the one canonical copy).
  if (Array.isArray(data)) data = data.filter((n) => !isAlex(n));
  else if (data && Array.isArray(data['@graph'])) data['@graph'] = data['@graph'].filter((n) => !isAlex(n));
  else if (isAlex(data)) return '';
  data = refPeople(data);
  if (Array.isArray(data) && data.length === 0) return '';
  if (Array.isArray(data) && data.length === 1) data = data[0];
  return json.includes('\n') ? JSON.stringify(data, null, 2) : JSON.stringify(data);
}

function transform(html, file) {
  // 1. head markers
  if (!html.includes('<!-- network:head:start -->')) {
    if (!html.includes('</head>')) throw new Error(`${file}: no </head>`);
    html = html.replace('</head>', '<!-- network:head:start -->\n<!-- network:head:end -->\n</head>');
  }
  // 2. footer markers around the existing site footer
  if (!html.includes('<!-- network:footer:start -->')) {
    const start = html.search(/<footer class="site-footer"/);
    const end = html.indexOf('</footer>', start);
    if (start < 0 || end < 0) throw new Error(`${file}: no <footer class="site-footer">`);
    html = `${html.slice(0, start)}<!-- network:footer:start -->\n<!-- network:footer:end -->${html.slice(end + '</footer>'.length)}`;
  }

  // Work on everything outside the managed head block.
  const [pre, rest] = html.split('<!-- network:head:start -->');
  const [, post] = rest.split('<!-- network:head:end -->');
  let outside = pre + '\u0000' + post;

  // 3. old hand-written gtag snippets
  outside = outside.replace(/<script[^>]*googletagmanager\.com\/gtag\/js[^>]*><\/script>\s*<script>[\s\S]*?gtag\('config'[\s\S]*?<\/script>\s*/g, '');
  // 4. hand-written Person JSON-LD
  outside = outside.replace(/(<script type="application\/ld\+json">)([\s\S]*?)(<\/script>)(\s*)/g, (m, open, body, close, ws) => {
    if (!body.includes('Person')) return m;
    const lead = body.match(/^\s*/)[0];
    const trail = body.match(/\s*$/)[0];
    const cleaned = cleanJsonLd(body.trim());
    if (cleaned === null) throw new Error(`${file}: unparseable JSON-LD with a Person`);
    if (cleaned === '') return '';
    const indent = lead.includes('\n') ? lead.split('\n').pop() : '';
    const pretty = cleaned.includes('\n') ? cleaned.split('\n').map((l, i) => (i ? indent + l : l)).join('\n') : cleaned;
    return `${open}${lead}${pretty}${trail}${close}${ws}`;
  });
  // 5. twitter meta: name= not property=, one handle
  outside = outside.replace(/<meta property="twitter:/g, '<meta name="twitter:');
  outside = outside.replace(/\s*<meta name="twitter:site" content="[^"]*">/g, '');
  outside = outside.replace(/(<meta name="twitter:creator" content=")[^"]*(")/g, `$1${esc(twitterSite)}$2`);

  const [a, b] = outside.split('\u0000');
  html = `${a}<!-- network:head:start -->${rest.split('<!-- network:head:end -->')[0]}<!-- network:head:end -->${b}`;

  html = replaceBlock(html, 'head', headBlock);
  html = replaceBlock(html, 'footer', footerBlock);

  // Checks
  const gtag = (html.match(/googletagmanager\.com\/gtag\/js/g) || []).length;
  const persons = (html.match(/"@type"\s*:\s*"Person"/g) || []).length;
  const tsite = (html.match(/name="twitter:site"/g) || []).length;
  if (gtag !== 1) throw new Error(`${file}: expected one gtag loader, found ${gtag}`);
  if (persons !== 1) throw new Error(`${file}: expected one Person JSON-LD, found ${persons}`);
  if (tsite !== 1) throw new Error(`${file}: expected one twitter:site, found ${tsite}`);
  return html;
}

function* pages(dir) {
  for (const name of readdirSync(dir)) {
    if (['.git', 'network', 'node_modules', 'scripts'].includes(name)) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) yield* pages(p);
    else if (name.endsWith('.html')) yield p;
  }
}

let n = 0;
let changed = 0;
for (const p of pages(ROOT)) {
  const file = relative(ROOT, p);
  const html = readFileSync(p, 'utf8');
  const out = transform(html, file);
  n++;
  if (out !== html) { writeFileSync(p, out); changed++; }
}
console.log(`apply-network: ${n} pages, ${changed} changed`);
